# Generated by Django 5.1.3 on 2024-11-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallesh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mallesh',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='mallesh',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
